### ISSUE TITLE
Server crash on startup switching from 1.2.0 to 2.0.0

### ISSUE THREAD

**Issue by VallenFrostweaver** [salvadormg15/Rubber-Duck#6]
Minecraft 1.16.5
Forge 36.2.2
Rubber Duck 2.0.0

Used this on a server and it crashes. Had to revert to 1.2.0 for it to work again.

Crash Report: https://www.toptal.com/developers/hastebin/ejetuxifon.rb

**Comment by salvadormg15** [comment]
Solved! Take a look to the new version
